### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by sudhanshu16** [sudhanshu16/openwrt-firmware-selector#26]
Right now the code is a bit of mess. It is all (almost) in one single file and needs some cleanup. 
It would be great to have a refactoring done for the same.

Let's discuss and do the necessary changes.
Cheers!

**Comment by hippietilley** [comment]
I can take a look at this

**Comment by sudhanshu16** [comment]
@hippietilley Thanks for the interest. Before you start working, I would like to discuss what all changes to be made under this refactoring. 
Can you please prepare a list of changes and we can discuss that :)

**Comment by hippietilley** [comment]
@sudhanshu16 yeah, sure! I've only been writing JS for a few months so discussion would be great! Things I noticed in my preliminary look over the project: 
 - `App.js` and the `components` folder all look pretty good.
 - `home.js` is where most of the work needs to be done.
 - I'd like to see if there's a better way to import all the things from `@material-ui/core` because the current way takes up a lot of space.
 - It looks like there are a lot of functional... functions that can be refactored into a more functional component to help separate the UI stuff from the logic a bit.
 
Thoughts? Concerns?

**Comment by sudhanshu16** [comment]
Great ideas @hippietilley!

* You don't need to change the way imports are happening right now. The requirement is to segregate the functionalities into separate functional components.
* Yup there are a lot of business logic(functions). I would like to know a good way to separate them from the component itself.
Cheers! 

Maybe you can raise a PR already since I see some good ideas and we can discuss/collaborate the rest in the comments.

**Comment by hippietilley** [comment]
Sounds good! I probably won't have a PR ready till this weekend at the earliest due to work/school stuff.

**Comment by hippietilley** [comment]
I haven't had a chance to touch this yet. So, if someone else is interested that's fine with me.

**Comment by sudhanshu16** [comment]
Did this recently. Ported the project to typescript.
